name: qiime2-amplicon-2025.7
channels:
  - qiime2/label/r2025.7
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - qiime2=2025.7
  - q2cli=2025.7
  - q2templates=2025.7
  - q2-types=2025.7
  - q2-alignment
  - q2-composition
  - q2-cutadapt
  - q2-dada2
  - q2-deblur
  - q2-demux
  - q2-diversity
  - q2-diversity-lib
  - q2-emperor
  - q2-feature-classifier
  - q2-feature-table
  - q2-fragment-insertion
  - q2-longitudinal
  - q2-metadata
  - q2-mystery-stew
  - q2-phylogeny
  - q2-quality-control
  - q2-quality-filter
  - q2-sample-classifier
  - q2-stats
  - q2-taxa
  - q2-vizard
  - q2-vsearch
  - python=3.9
  - pandas
  - numpy
  - matplotlib
  - seaborn
  - scikit-learn
  - biom-format
  - h5py
  - pip
  - pip:
    - redbiom
